name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      Solution_Name: DafDev.Katas.MarsRover.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: tests\DafDev.Katas.MarsRover.Navigation.Application.Tests\DafDev.Katas.MarsRover.Navigation.Application.Tests.csproj                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 7.0.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '7.0.x'

      # restore dependencies     
      - name: Install dependencies
        run: dotnet restore
      
      # Build
      - name: Build
        run: dotnet build --no-restore
      
      # Run Tests
      - name: Execute unit tests
        run: dotnet test --no-build
